name: update-profile-resume
run-name: ${{ github.actor }} is updating Resume
on: [push]
jobs:
  create-pdf:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Render HTML
        run: "npx resumed render"
      - name: Create PDF
        run: "npm run run-pdf"