name: update-profile-resume

run-name: ${{ github.actor }} is updating Resume
on: [push]

permissions:
  contents: write

jobs:
  create-pdf:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i
      - name: Create PDF
        run: |
          node index.js